version: '3.3'
services:    
    srv_mtga_be:
        build:
            context: .
            dockerfile: ./srv_mtga_be/Dockerfile
        environment:
            - MONGO_USER=root
            - MONGO_PASS=pass
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - GRPC_PORT=50051
        ports:
            - "50051:50051"
        depends_on:
            - mongo
    srv_mtga_be_fa:
        build:
            context: .
            dockerfile: ./srv_mtga_be_fa/Dockerfile
        environment:
            - MONGO_USER=root
            - MONGO_PASS=pass
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
        ports:
            - "8000:8000"
    srv_mtga_fe:
        build:
            context: .
            dockerfile: ./srv_mtga_fe/Dockerfile
        environment:
            - GRPC_SERVER=srv_mtga_be
            - GRPC_PORT=50051
            - API_SERVER=http://srv_mtga_be_fa
            - API_PORT=8000
        depends_on:
            - srv_mtga_be
    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - mongo:/data/db
        ports:
            - "27017:27017"
volumes:
    mongo: