version: '3.3'
services:    
    srv_mtga_be:
        build:
            context: ./srv_mtga_be
        environment:
            - SERVICE_PORT=50051
        ports:
            - "50001:50051"

    srv_mtga_fe:
        build:
            context: ./srv_mtga_fe
        environment:
            - GRPC_PRODUCER_HOST=srv_mtga_be
            - GRPC_PRODUCER_PORT=50051
        depends_on:
            - srv_mtga_be