version: '3.3'
services:    
    srv_mtga_be:
        build:
            context: .
            dockerfile: ./srv_mtga_be/Dockerfile
        environment:
            - MONGO_USER=root
            - MONGO_PASS=pass
            - MONGO_HOST=mongodb
        ports:
            - "50001:50051"
    srv_mtga_be_fa:
        build:
            context: .
            dockerfile: ./srv_mtga_be_fa/Dockerfile
        ports:
            - "8000:8000"
    srv_mtga_fe:
        build:
            context: .
            dockerfile: ./srv_mtga_fe/Dockerfile
        environment:
            - MTGA_BE_IP=srv_mtga_be
            - MTGA_BE_PORT=50051
        depends_on:
            - srv_mtga_be
    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - mongo:/data/db
        ports:
            - "27017:27017"
volumes:
    mongo: