# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mtg_card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0emtg_card.proto"\x0f\n\rEmptyMesssage"\x1e\n\x0cPingResponse\x12\x0e\n\x06result\x18\x01 \x01(\t24\n\x0b\x43\x61rdService\x12%\n\x04Ping\x12\x0e.EmptyMesssage\x1a\r.PingResponseb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "mtg_card_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _EMPTYMESSSAGE._serialized_start = 18
    _EMPTYMESSSAGE._serialized_end = 33
    _PINGRESPONSE._serialized_start = 35
    _PINGRESPONSE._serialized_end = 65
    _CARDSERVICE._serialized_start = 67
    _CARDSERVICE._serialized_end = 119
# @@protoc_insertion_point(module_scope)
